" Don't try to be vi compatible
set nocompatible

" Helps force plugins to load correctly when it's turned back on below
filetype off

" TODO: load plugins here

" Set runtime path to include bundle directory
set runtimepath^=~/.vim/bundle/vim-es6-2.1

" Turn on syntax highlighting
syntax on

" For plugins to load correctly
filetype plugin indent on

" Pick a leader key
let mapleader = ","

" Security
set modelines=0

" Show line numbers
set number

" Show file status
set ruler

" Blink cursor on error instead of beeping
set visualbell
set t_vb=

" Encoding
set encoding=utf-8

" Whitespace
set wrap
set textwidth=79
set formatoptions=tcqrn1
set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab
set noshiftround

autocmd Filetype python setlocal expandtab tabstop=2 shiftwidth=2
autocmd Filetype python highlight Comment ctermfg=2
autocmd Filetype javascript highlight Comment ctermfg=2
augroup filetype javascript syntax=javascript

" Cursor motion
set scrolloff=3
set backspace=indent,eol,start
set matchpairs+=<:> " use % to jump between pairs
runtime! macros/matchit.vim

" Move up/down editor lines
nnoremap j gj
nnoremap k gk

" Allow hidden buffers
set hidden

" Rendering
set ttyfast

" Status bar
set laststatus=2

" Last line
set showmode
set showcmd

" Searching
nnoremap / /\v
vnoremap / /\v
set hlsearch
set incsearch
set ignorecase
set smartcase
set showmatch
map <leader><space> :let @/=''<cr> " clear search

" Remap help key
inoremap <F1> <ESC>:set invfullscreen<CR>a
nnoremap <F1> :set invfullscreen <CR>
vnoremap <F1> :set invfullscreen <CR>

" Textmate holdouts

" Formatting
map <leader>q gqip

" Visualize tabs and newlines
set listchars=tab:▸\ ,eol:¬

" Uncomment this to enable by default:
" set list " To enable by default
" Or use your leader key + l to toggle on/off
map <leader>l :set list!<CR> " Toggle tabs and EOL

" Color scheme (terminal)
set t_Co=256
set background=dark
let g:solarized_termcolors=256
let g:solarized_termtrans=1
" put https://raw.github.com/altercation/vim-colors-solarized/master/colors/solarized.vim
" in ~/.vim/colors/ and uncomment:
" colorscheme solarized

" Easily toggle paste mode
set pastetoggle=<leader>v

" Other filetypes
au BufRead,BufNewFile *.thor set filetype=ruby

" Custom configuration based on terminal profile
let iterm_profile = $ITERM_PROFILE
if iterm_profile == "street"
  " Custom changes for street profile
  highlight lineNr ctermfg=246

elseif iterm_profile == "cyber"
  " Custom changes for cyber profile

elseif iterm_profile == "palendrome"
  " Custom changes for palendrome profile

elseif iterm_profile == "machine"
  " Custom changes for machine profile
  set laststatus=1
  set background=light

elseif iterm_profile == "samaritan"
  " Custom changes for machine profile
  set nonumber
  set noruler
  set laststatus=1
  set background=light

elseif iterm_profile == "clean"
  " Custom changes for machine profile
  set nonumber
  set noruler
  set laststatus=1

elseif iterm_profile == "basic"
  " Custom changes for default profile

endif

